export const sampleReports = [
  {
    nomor: 1,
    namaBarang: "Laptop Lenovo ThinkPad",
    tanggalMinjam: "2025-10-01",
    tanggalKembali: "2025-10-05",
    status: "Dikembalikan",
    warnaStatus: "green",
    keterangan: "Tidak ada kerusakan",
  },
  {
    nomor: 2,
    namaBarang: "Proyektor Epson",
    tanggalMinjam: "2025-10-03",
    tanggalKembali: "2025-10-04",
    status: "Dipinjam",
    warnaStatus: "blue",
    keterangan: "Digunakan untuk presentasi",
  },
  {
    nomor: 3,
    namaBarang: "Printer Canon",
    tanggalMinjam: "2025-10-02",
    tanggalKembali: "2025-10-06",
    status: "Terlambat",
    warnaStatus: "red",
    keterangan: "Belum dikembalikan, lewat batas waktu",
  },
  {
    nomor: 4,
    namaBarang: "Kamera DSLR Nikon",
    tanggalMinjam: "2025-09-28",
    tanggalKembali: "2025-10-02",
    status: "Dikembalikan",
    warnaStatus: "green",
    keterangan: "Lensa bersih",
  },
  {
    nomor: 5,
    namaBarang: "Meja Lipat",
    tanggalMinjam: "2025-10-04",
    tanggalKembali: "2025-10-04",
    status: "Dipinjam",
    warnaStatus: "blue",
    keterangan: "Untuk rapat mingguan",
  },
];
