const sampleDataList = [
  {
    id_return: "RET001",
    nama_user: "Dafa",
    barang: "Laptop Lenovo ThinkPad",
    kode_barang: "BRG001",
    jumlah: 1,
    tanggal_kembali: "2025-10-15",
    kondisi_awal: "Baik",
    kondisi_saat_ini: "Baik",
  },
  {
    id_return: "RET002",
    nama_user: "Siti",
    barang: "Monitor Samsung 24 Inch",
    kode_barang: "BRG002",
    jumlah: 2,
    tanggal_kembali: "2025-10-16",
    kondisi_awal: "Baik",
    kondisi_saat_ini: "Cukup",
  },
  {
    id_return: "RET003",
    nama_user: "Budi",
    barang: "Meja Kerja Kayu",
    kode_barang: "BRG003",
    jumlah: 1,
    tanggal_kembali: "2025-10-17",
    kondisi_awal: "Cukup",
    kondisi_saat_ini: "Rusak",
  },
  {
    id_return: "RET004",
    nama_user: "Rina",
    barang: "Proyektor Epson",
    kode_barang: "BRG005",
    jumlah: 1,
    tanggal_kembali: "2025-10-18",
    kondisi_awal: "Baik",
    kondisi_saat_ini: "Baik",
  },
  {
    id_return: "RET005",
    nama_user: "Admin",
    barang: "Kursi Kantor",
    kode_barang: "BRG004",
    jumlah: 3,
    tanggal_kembali: "2025-10-19",
    kondisi_awal: "Baik",
    kondisi_saat_ini: "Cukup",
  },
];

const sampleDataHistory = [
  {
    id_return: "RET001",
    nama_user: "Dafa",
    barang: "Laptop Lenovo ThinkPad",
    kode_barang: "BRG001",
    jumlah: 1,
    kondisi_akhir: "Baik",
    status: "Selesai",
  },
  {
    id_return: "RET002",
    nama_user: "Siti",
    barang: "Monitor Samsung 24 Inch",
    kode_barang: "BRG002",
    jumlah: 2,
    kondisi_akhir: "Cukup",
    status: "Selesai",
  },
  {
    id_return: "RET003",
    nama_user: "Budi",
    barang: "Meja Kerja Kayu",
    kode_barang: "BRG003",
    jumlah: 1,
    kondisi_akhir: "Rusak",
    status: "Selesai",
  },
  {
    id_return: "RET004",
    nama_user: "Rina",
    barang: "Proyektor Epson",
    kode_barang: "BRG005",
    jumlah: 1,
    kondisi_akhir: "Baik",
    status: "Selesai",
  },
  {
    id_return: "RET005",
    nama_user: "Admin",
    barang: "Kursi Kantor",
    kode_barang: "BRG004",
    jumlah: 3,
    kondisi_akhir: "Cukup",
    status: "Selesai",
  },
];

const sampleDataRequest = [
  {
    id_return: "RET001",
    nama_user: "Dafa",
    barang: "Laptop Lenovo ThinkPad",
    kode_barang: "BRG001",
    tanggal_kembali: "2025-10-15",
    jumlah: 1,
    kondisi_akhir: "Baik",
  },
  {
    id_return: "RET002",
    nama_user: "Siti",
    barang: "Monitor Samsung 24 Inch",
    kode_barang: "BRG002",
    tanggal_kembali: "2025-10-16",
    jumlah: 2,
    kondisi_akhir: "Cukup",
  },
  {
    id_return: "RET003",
    nama_user: "Budi",
    barang: "Meja Kerja Kayu",
    kode_barang: "BRG003",
    tanggal_kembali: "2025-10-17",
    jumlah: 1,
    kondisi_akhir: "Rusak",
  },
  {
    id_return: "RET004",
    nama_user: "Rina",
    barang: "Proyektor Epson",
    kode_barang: "BRG005",
    tanggal_kembali: "2025-10-18",
    jumlah: 1,
    kondisi_akhir: "Baik",
  },
  {
    id_return: "RET005",
    nama_user: "Admin",
    barang: "Kursi Kantor",
    kode_barang: "BRG004",
    tanggal_kembali: "2025-10-19",
    jumlah: 3,
    kondisi_akhir: "Cukup",
  },
];

export {
  sampleDataList,
  sampleDataHistory,
  sampleDataRequest,
};
