const sampleDataRequest = [
  {
    id_request: "REQ001",
    nama_user: "Dafa",
    barang: "Laptop Lenovo ThinkPad",
    jumlah: 1,
    tanggal_pengajuan: "2025-10-18",
  },
  {
    id_request: "REQ002",
    nama_user: "Siti",
    barang: "Monitor Samsung 24 Inch",
    jumlah: 2,
    tanggal_pengajuan: "2025-10-17",
  },
  {
    id_request: "REQ003",
    nama_user: "Admin",
    barang: "Meja Kerja Kayu",
    jumlah: 1,
    tanggal_pengajuan: "2025-10-16",
  },
  {
    id_request: "REQ004",
    nama_user: "Budi",
    barang: "Kursi Kantor",
    jumlah: 4,
    tanggal_pengajuan: "2025-10-15",
  },
  {
    id_request: "REQ005",
    nama_user: "Rina",
    barang: "Proyektor Epson",
    jumlah: 1,
    tanggal_pengajuan: "2025-10-14",
  },
];

const sampleDataHistory = [
  {
    id_peminjaman: "PIN001",
    nama_user: "Dafa",
    barang: "Laptop Lenovo ThinkPad",
    jumlah: 1,
    tanggal_pinjam: "2025-10-10",
    tanggal_kembali: "2025-10-15",
    kondisi_barang: "Baik",
    status: "Selesai",
  },
  {
    id_peminjaman: "PIN002",
    nama_user: "Siti",
    barang: "Monitor Samsung 24 Inch",
    jumlah: 2,
    tanggal_pinjam: "2025-10-09",
    tanggal_kembali: "2025-10-16",
    kondisi_barang: "Baik",
    status: "Terlambat",
  },
  {
    id_peminjaman: "PIN003",
    nama_user: "Admin",
    barang: "Meja Kerja Kayu",
    jumlah: 1,
    tanggal_pinjam: "2025-10-08",
    tanggal_kembali: "2025-10-12",
    kondisi_barang: "Cukup",
    status: "Selesai",
  },
  {
    id_peminjaman: "PIN004",
    nama_user: "Budi",
    barang: "Kursi Kantor",
    jumlah: 4,
    tanggal_pinjam: "2025-10-07",
    tanggal_kembali: "2025-10-14",
    kondisi_barang: "Baik",
    status: "Selesai",
  },
  {
    id_peminjaman: "PIN005",
    nama_user: "Rina",
    barang: "Proyektor Epson",
    jumlah: 1,
    tanggal_pinjam: "2025-10-06",
    tanggal_kembali: "2025-10-13",
    kondisi_barang: "Rusak",
    status: "Terlambat",
  },
];

const sampleDataList = [
  {
    id_peminjaman: "PIN001",
    nama_user: "Dafa",
    barang: "Laptop Lenovo ThinkPad",
    jumlah: 1,
    tanggal_pinjam: "2025-10-10",
    tanggal_kembali: "2025-10-15",
  },
  {
    id_peminjaman: "PIN002",
    nama_user: "Siti",
    barang: "Monitor Samsung 24 Inch",
    jumlah: 2,
    tanggal_pinjam: "2025-10-09",
    tanggal_kembali: "2025-10-16",
  },
  {
    id_peminjaman: "PIN003",
    nama_user: "Admin",
    barang: "Meja Kerja Kayu",
    jumlah: 1,
    tanggal_pinjam: "2025-10-08",
    tanggal_kembali: "2025-10-12",
  },
  {
    id_peminjaman: "PIN004",
    nama_user: "Budi",
    barang: "Kursi Kantor",
    jumlah: 4,
    tanggal_pinjam: "2025-10-07",
    tanggal_kembali: "2025-10-14",
  },
  {
    id_peminjaman: "PIN005",
    nama_user: "Rina",
    barang: "Proyektor Epson",
    jumlah: 1,
    tanggal_pinjam: "2025-10-06",
    tanggal_kembali: "2025-10-13",
  },
];

export { sampleDataRequest, sampleDataHistory, sampleDataList };
