export const sampleStatus = [
  {
    nomor: 1,
    namaBarang: "Laptop Lenovo ThinkPad",
    tanggalMinjam: "2025-10-01",
    jatuhTempo: "2025-10-05",
    status: "Dipinjam",
    warnaStatus: "blue",
    keterangan: "1 hari lagi jatuh tempo",
  },
  {
    nomor: 2,
    namaBarang: "Proyektor Epson",
    tanggalMinjam: "2025-10-03",
    jatuhTempo: "2025-10-04",
    status: "Dipinjam",
    warnaStatus: "blue",
    keterangan: "5 hari lagi jatuh tempo",
  },
  {
    nomor: 3,
    namaBarang: "Printer Canon",
    tanggalMinjam: "2025-10-02",
    jatuhTempo: "2025-10-06",
    status: "Terlambat",
    warnaStatus: "red",
    keterangan: "Melewati tempo",
  },
  {
    nomor: 4,
    namaBarang: "Kamera DSLR Nikon",
    tanggalMinjam: "2025-09-28",
    jatuhTempo: "2025-10-02",
    status: "Terlambat",
    warnaStatus: "red",
    keterangan: "Melewati tempo",
  },
  {
    nomor: 5,
    namaBarang: "Meja Lipat",
    tanggalMinjam: "2025-10-04",
    jatuhTempo: "2025-10-04",
    status: "Dipinjam",
    warnaStatus: "blue",
    keterangan: "4 hari lagi jatuh tempo",
  },
];
