export const sampleBorrow = [
  {
    nomor: 1,
    barang: "Laptop Lenovo ThinkPad",
    kategori: "Elektronik",
    kondisi: "Baik",
    status: "Tersedia",
    warnaStatus: "green",
    stok: 5,
  },
  {
    nomor: 2,
    barang: "Proyektor Epson",
    kategori: "Elektronik",
    kondisi: "Baik",
    status: "Tersedia",
    warnaStatus: "green",
    stok: 3,
  },
  {
    nomor: 3,
    barang: "Meja Lipat",
    kategori: "Furniture",
    kondisi: "Baik",
    status: "Tersedia",
    warnaStatus: "green",
    stok: 10,
  },
  {
    nomor: 4,
    barang: "Kamera DSLR Nikon",
    kategori: "Elektronik",
    kondisi: "Baik",
    status: "Dipinjam",
    warnaStatus: "red",
    stok: 0,
  },
  {
    nomor: 5,
    barang: "Whiteboard",
    kategori: "Alat Tulis",
    kondisi: "Cukup",
    status: "Dipinjam",
    warnaStatus: "red",
    stok: 0,
  },
];
